### ISSUE TITLE
failed to process tlog record (bucket:create)

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/minio#75]
I got this error on one of my minio.
here is the logs of the container: https://gist.github.com/zaibon/eaef14c83111b8623f2bf7c10f97ca3f

I don't know if this error means the synchronisation is not happening or not.
But it does mess with the watchdog of the tlog syncer at least. Which in turn trigger self-healing in a loop to restart the minio

**Comment by zaibon** [comment]
I also sometime see logs like 
```
2019/02/07 13:11:01 [minio.21ec3054-56ce-4909-9904-cb078d6a9889]{"action":"bucket:create","error":"Bucket exists: ","level":"error","msg":"failed to process tlog record","namespace":"b42486c9-a65b-4da6-bed6-e1021c48ddbc_tlog","subsystem":"sync","time":"2019-02-07T13:11:01Z","tlog":"172.16.46.114:1029"}
```
I don't know if this is related

**Comment by muhamadazmy** [comment]
This error happens when a slave minio fails to apply the action required by the tlog record. When u create a bucket on master, the buckt create action is recorded in the master tlog. the passive minio reads this record and tries to apply the same action (in this case bucket:create) but it fails to apply it because of the error: "Bucket exists". 

the reason u get this error can be due to different reasons:
- a failed delete on passive ! but this should be in the logs somewhere
- the tlog is replaying again (may be a restart before the state of the tlog was recorded) so it tries to run the same actions again.
- dirty meta data directory? (due to a disk reuse in a new deployment, may be)

**Comment by muhamadazmy** [comment]
I understand this can really miss with the watchdog of the passive minio. From minio side, we can start a list of errors that are not critical and doesn't indicate a failed synchronization, and ignore them (don't log them), may be output them only as a warning

**Comment by zaibon** [comment]
yep I think this is needed. We should be able to replay a full tlog from scratch even if the minio has already half of the state. So bucket creation method should not fail if the bucket already exists, same for bucket delete, it should't not fail if there is already no bucket.

So yeah, let's list all the tlog action possible and decide what is acceptable in term or error.
