### ISSUE TITLE
tlog synchronisation fails with: connect: cannot assign requested address"

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/minio#77]
I saw one of my passive minio getting redeploying forever. 
After checking the logs I saw: 
```
2019/03/13 13:50:52 [minio.29e99b48-a007-4f59-8335-4c6f12db2384]{"error":"dial tcp 172.20.18.50:1032: connect: cannot assign requested address","level":"error","master":false,"msg":"failed to write transaction log","namespace":"d42e487f-52d4-4f55-ac3d-2ce7065a0b54_tlog","subsystem":"tlog","time":"2019-03-13T13:50:52Z","tlog":"172.20.18.50:1032"}
```
So for some reason the minio cannot connect to the its own tlog 0-db to write the metadata.

**Comment by zaibon** [comment]
Here is the full logs of the passive container before it got redeployed: https://gist.github.com/zaibon/ae24cf08c74054b88359fae0007355cb

Seems here the problem doesn't come from a connection error, but some error during the replay of the tlog.

**Comment by muhamadazmy** [comment]
Can u reach this address from minio container?

**Comment by zaibon** [comment]
@muhamadazmy yes the zerodb was actually reachable.
I've been search a bit about `connect: cannot assign requested address`, it seems this happens before the connection is even created so problem is not about 0-db reachability

**Comment by zaibon** [comment]
I wonder if the don't have 2 different issues here. 
Cause from my inspection of the logs it seems the error comes from lines like this: https://gist.github.com/zaibon/ae24cf08c74054b88359fae0007355cb#file-gistfile1-txt-L30
`{"error":"open /minio_metadata/objects/awscli-mint-test-bucket-15348/prefix/directory/datafile-1-MB: not a directory","key":"awscli-mint-test-bucket-15348/prefix/directory/datafile-1-MB","level":"error","msg":"failed to write metadata","namespace":"d42e487f-52d4-4f55-ac3d-2ce7065a0b54","subsystem":"disk","time":"2019-03-13T14:34:08Z"}`

The error is "Not a directory" and indeed it seems that ` /minio_metadata/objects/awscli-mint-test-bucket-15348/prefix/directory` is actually a file. I have no knowledge of how the layout of the metadata is supposed to look like but that doesn't sounds right here.

**Comment by muhamadazmy** [comment]
I am working on reporducing the issue now, and from the logs above, it might be bug in how we handle `prefixes`. Since s3 itself doesn't have concept of directories, it's rather `prefixes` it's possible to have a `a/b` as a file and also `a/b/c` as a file! but this won't work with our structures.

Anyway, once we reproduce the issue, we can be sure.

**Comment by muhamadazmy** [comment]
Updates so far:
- awscli mint tests on master, although they seem to `pass` i can see some errors in the logs with the same error above. but they still report success anyway
- it happens on the master minio, so it's not "for sure"  a slave or synchronization issue. the issue is detected because the slave just can't apply the same meta as the master, but it detects as failure to sync.
- I will have to look deeper why we end up in this state, i will dive in mint tests for "awscli". 
- I think it might be related to how s3 actually support directories (via prefix + delimiter) as explained in the previous comment. in that case it wouldn't be possible to fix, and we will have just to ignore the error for now

**Comment by zaibon** [comment]
https://github.com/threefoldtech/minio/commit/550a9084a72200d1104020e5bc0a11f90b45ddce
